apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
  - image: ulan025/flask:1.0
    name: wordpress
    ports:
    - containerPort: 5000
  # imagePullSecrets:
  # - name: my-secret