apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
  - image: wordpress
    name: wordpress
    env:
    - name: password
      valueFrom:
        secretKeyRef:
          name: secret-pass
          key: pass
    - name: user
      valueFrom:
        secretKeyRef:
          name: secret-pass
          key: user