apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  labels:
    app: devops-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
      - name: devops-api
        image: ulan025/node-back:1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: DB
          value: devops_db
        - name: DBUSER
          value: devops_user
        - name: DBPASS
          value: password
        - name: DBHOST
          value: mysql
        - name: DBPORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-api
spec:
  selector:
    app: devops-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
