apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web
  labels:
    app: devops-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-web
  template:
    metadata:
      labels:
        app: devops-web
    spec:
      containers:
      - name: devops-web
        image: ulan025/node-front:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_HOST
          value: http://devops-api:3001
        
---
apiVersion: v1
kind: Service
metadata:
  name: devops-web
spec:
  selector:
    app: devops-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
